import Header from "@/src/components/Header/Header";
import { Box, Stack, Container } from "@mui/material";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ margin: 0, background: "#3D3C42" }}
      >
        <Header />
        <Container>{children}</Container>
      </body>
    </html>
  );
}
